name: Publish package to GitHub Packages
on:
  push:
    branches: [ release ]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@sqa.iste.uni-stuttgart.de"
          git config user.name "GitHub Actions Robot"
      - name: Publish package
        run: mvn --batch-mode release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
